package com.example.iterativechallenger.core.exceptions

import java.lang.Exception

class ResourceNotFoundThrowable: Throwable("Recurso n√£o encontrado")